package cn.itcast.cxf.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-11-30T16:38:38.274+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "MobileAddressServiceService", 
                  wsdlLocation = "http://localhost:8888/cxf_jaxws_spring/services/mobile?wsdl",
                  targetNamespace = "http://server.cxf.itcast.cn/") 
public class MobileAddressServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cxf.itcast.cn/", "MobileAddressServiceService");
    public final static QName MobileAddressServicePort = new QName("http://server.cxf.itcast.cn/", "MobileAddressServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/cxf_jaxws_spring/services/mobile?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MobileAddressServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/cxf_jaxws_spring/services/mobile?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MobileAddressServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileAddressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileAddressServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MobileAddressServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MobileAddressServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MobileAddressServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MobileAddressService
     */
    @WebEndpoint(name = "MobileAddressServicePort")
    public MobileAddressService getMobileAddressServicePort() {
        return super.getPort(MobileAddressServicePort, MobileAddressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileAddressService
     */
    @WebEndpoint(name = "MobileAddressServicePort")
    public MobileAddressService getMobileAddressServicePort(WebServiceFeature... features) {
        return super.getPort(MobileAddressServicePort, MobileAddressService.class, features);
    }

}
